# Versioning System
XTENDED_VERSION = v1.0

ifndef XTENDED_BUILD_TYPE
    XTENDED_BUILD_TYPE := OFFICIAL
endif

# Set all versions
DATE := $(shell date -u +%Y%m%d)
XTENDED_VERSION := $(TARGET_PRODUCT)-$(XTENDED_VERSION)-$(DATE)-$(shell date -u +%H%M)-$(XTENDED_BUILD_TYPE)
TARGET_BACON_NAME := $(XTENDED_VERSION)

PRODUCT_PROPERTY_OVERRIDES += \
    BUILD_DISPLAY_ID=$(BUILD_ID) \
    ro.xtended.version=$(XTENDED_VERSION) \
    ro.mod.version=$(XTENDED_BUILD_TYPE)-$(XTENDED_VERSION)-$(DATE)
